name: kitchen_inventory
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0  # For "Remember Me" feature
  google_fonts: ^6.1.0  # For better typography 
    
  # firebase_auth: ^5.5.2
  # cloud_firestore: ^4.13.0
  # firebase_core: ^2.15.0
  # # flutter_blur: ^3.0.0
  hive: ^2.2.3  # Local storage
  hive_flutter: ^1.1.0  # Flutter Hive helper
  # path_provider: ^2.0.11  # Get local file paths

  cupertino_icons: ^1.0.8
  fl_chart: ^1.0.0
  step_progress_indicator: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/background.jpg
    - assets/dashboard_backgraund_2.jpg
    - assets/dashboard_backgraund_2.jpg

  uses-material-design: true
